# Generated by Django 6.0 on 2026-01-16 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('teams', '0002_userprofile_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugins', to='teams.team')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='UserPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugins', to='teams.userprofile')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
