services:
  web:
    build:
      context: .
    env_file: .env
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app1.rule=Host(`brueggerei.superservice-international.com`)"
      - "traefik.http.services.app1.loadbalancer.server.port=8000"
      - "traefik.http.routers.app1.entrypoints=websecure"
      - "traefik.http.routers.app1.tls.certresolver=letsencrypt"
      - "docker-rollout.pre-stop-hook=touch /tmp/drain && sleep 10"
    healthcheck:
      test: test ! -f /tmp/drain
      interval: 5s
      retries: 1
    depends_on:
      - postgres
      - memcached

  postgres:
    image: postgres:16
    env_file: .env
    volumes:
      - ./backups/:/db_backups/
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
  
  memcached:
    env_file: .env
    image: memcached
    restart: always

volumes:
  postgres_data: {}
  postgres_backup: {}

networks:
  web:
    external: true
