services:
  web:
    build:
      context: .
    command: sh start.sh
    env_file: .env
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    networks:
      - web
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app1.rule=Host(`brueggerei.superservice-international.com`) && !PathPrefix(`/static`) && !PathPrefix(`/media`)"
      - "traefik.http.services.app1.loadbalancer.server.port=8000"
      - "traefik.http.routers.app1.entrypoints=websecure"
      - "traefik.http.routers.app1.tls.certresolver=letsencrypt"
      - "docker-rollout.pre-stop-hook=touch /tmp/drain && sleep 10"
    healthcheck:
      test: test ! -f /tmp/drain
      interval: 5s
      retries: 1
    depends_on:
      - postgres
      - memcached
      - nginx

  nginx:
    image: nginx:alpine
    volumes:
      - ./staticfiles:/data/static:ro
      - ./media:/data/media:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static.rule=Host(`brueggerei.superservice-international.com`) && (PathPrefix(`/static`) || PathPrefix(`/media`))"
      - "traefik.http.routers.static.entrypoints=websecure"
      - "traefik.http.routers.static.tls.certresolver=letsencrypt"
      - "traefik.http.services.static.loadbalancer.server.port=80"

  postgres:
    image: postgres:16
    env_file: .env
    volumes:
      - ./backups/:/db_backups/
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    networks:
      - backend

  memcached:
    env_file: .env
    image: memcached
    restart: always
    networks:
      - backend

volumes:
  postgres_data: {}
  postgres_backup: {}

networks:
  web:
    external: true
  backend:
